version: '3'

services:
  nginx-fs:
    image: zcecc22/nginx-fs:latest
    ports:
      - '80:80'
    volumes:
      - /home/public:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  default:
    name: dev
    external: true
